README.md
package.json

Signed-off-by: ashleigh <ashleigh@wi-q.com>

Renamed package to nestjs-config

---

README.md
src/__tests__/__stubs__/config.stub.ts
src/__tests__/config.service.spec.ts
src/decorators/proxy.ts
src/module/config.service.ts

Implement feature recorded on the issue #8

Feature / Custom helpers

---

README.md
package.json
src/__tests__/config.module.spec.ts
src/__tests__/config.service.spec.ts
src/constants.ts
src/decorators/ConfigParam.ts
src/decorators/Configurable.ts
src/decorators/index.ts
src/module/config.module.ts
src/module/config.service.ts
src/utils.ts
yarn.lock

Ok, this code is pretty messy and has a lot of debug information -*i was in a hurry, sorry !*- , it maybe the 
first implementation of these decorators. so please don't accept this pull request yet!
it needs a lot of refactoring/cleaning and testing to make it pretty and efficient.
and the last thing, i think it works :smile_cat: 
so any help here on refactoring ?!

[feature]: `@ConfigParam()` and `@Configurable()` decorators for configurable providers

---

src/__tests__/config.module.spec.ts
src/decorators/Configurable.ts
src/module/config.service.ts
src/utils.ts

Added default value to configParam decorator

---

examples/basic/main.ts
examples/decorators/main.ts
examples/decorators/user.controller.ts
examples/typeorm/index.ts
package.json
src/__tests__/config.module.spec.ts
src/decorators/Configurable.ts

Fix issue #24 : The "this" value of decorated methods gets changed

---

src/module/config.service.ts

#55 Issue with TypeScript export of extended interface

Fixed issue with interface

---

README.md

Added basic info on modifyConfigName method

---

.github/issue_template.md

Added basic issue template

---

package.json
src/module/config.service.ts
yarn.lock

#63 
Updated dotenv and @types/dotenv to current versions and corrected exported interface name.

Updated dotenv type version

---

package.json

Fixed the link for repo for npm. Was irritating me

Fixed npm repo option in package

---

package-lock.json

fix dependencies lock

---

package.json
yarn.lock

Updated typescript

---

src/__tests__/config.module.spec.ts
src/module/config.module.ts

Added missing resolveRootPath method to configmodule

---

.github/issue_template.md

chore: turn `[ ]` to nice checkboxes in issue tpl

---

package-lock.json
package.json
yarn.lock

Fix for https://github.com/nestjs/nest/pull/2311

Update nestjs dependancies for axios 

---

README.md

Ammended readme with correct key

---

README.md
package.json

fixes #127 with documentation + added `@types/dotenv` to peer dependencies

Added dotenv options documentation

---

CONTRIBUTING.md
README.md

Improving the readme and repo standards etc

Added contributing file and readme contribute list

---

README.md

We should at least provide a small example to help people for a better understanding.

Fixed custom env file path section in the doc for better understanding

---

src/decorators/proxy.ts

This fixes the issue https://github.com/nestjsx/nestjs-config/issues/275

Fix issue #275: Unable to app.get(ConfigService) in main.ts with node 12.16

---

package-lock.json
yarn.lock

Reverts nestjsx/nestjs-config#287

Revert "Bump @nestjs/common from 6.10.11 to 6.11.11"

---

package.json

add ^8.0.0 version support to @nestjs/common peer dependency
